Frachtwerk/essencium-frontend

packages/app/src/components/layouts/AuthLayout.tsx
packages/app/src/components/layouts/PublicLayout.tsx
packages/app/src/pages/index.tsx
packages/app/src/pages/translations/index.tsx
packages/app/src/pages/users/[id].tsx
packages/app/src/pages/users/index.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/PersonalDataForm.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/ProfileSettingsForm.tsx
packages/lib/src/components/Role/components/RoleForm.tsx
packages/lib/src/components/Translations/Translations.tsx
packages/lib/src/utils/translations.ts
packages/types/src/base.ts
packages/types/src/user.ts
scripts/seed-db.ts

This PR includes the reactivity fix for updating / resetting translations. Additionally, it fixes the bug in the profile page.
[Here a Loom](https://www.loom.com/share/e83acf3e7465454a87e38cacd8e55c03?sid=bafd238d-f038-47e5-a393-7ffb2b8f48db)
**CLOSES**
Closes #366 
Closes #293

Fix translations

---

packages/docs/pages/devguide/pull-requests.mdx

This PR adds an icon beside the PR template in order to copy the content with just one click

docs: update pull-requests.mdx

---

packages/app/next.config.js
packages/app/src/pages/api/healthcheck.ts

This PR adds an healthcheck endpoint in order to determine whether the Next.js server is running.

feat: add healthcheck endpoint

---

packages/app/src/components/layouts/AuthLayout.tsx

This PR includes the persistence of the sidebar state inside the local storage.
**CLOSES**
Closes #389

feat: persist sidebar state in local storage

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/api/contact.ts
packages/app/src/components/layouts/AuthLayout.tsx
packages/app/src/pages/contact/index.tsx
packages/lib/src/components/Contact/Contact.tsx
packages/lib/src/components/Contact/components/ContactForm.tsx
packages/lib/src/components/Translations/Translations.tsx
packages/lib/src/utils/hasRequiredRights.ts
packages/types/src/contact.ts
packages/types/src/index.ts

In this PR the functionality for the contact form has been added. 
The user can now send a message to a given email address over the `ContactView`.

feat: add functionality to contact form

---

packages/app/next.config.js
packages/lib/src/layouts/AuthLayout.tsx

New pull request with correct version

393 routeguard to check for rights

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/docs/pages/devguide.mdx
packages/docs/pages/devguide/_meta.json
packages/docs/pages/devguide/seeding-database.mdx
scripts/seed-db.ts

This PR includes the adjustments for the seeding script. Now, a fixed set of dummy roles are created and the translations for them are resolved properly. I also wrote the documentation and updated the overview page of the dev guide by adding the missing subpages.
@PhilKsr Please test the seeding script according to the docs 👍 
**CLOSES**
Closes #253

253 update seed script with explicitly named roles

---

packages/lib/package.json
pnpm-lock.yaml

Fix https://github.com/Frachtwerk/essencium-frontend/security/dependabot/15

fix: fix babel vulnerability

---

packages/app/package.json
pnpm-lock.yaml

Fix https://github.com/Frachtwerk/essencium-frontend/security/dependabot/8

fix: fix chaijs vulnerability

---

pnpm-lock.yaml

https://github.com/Frachtwerk/essencium-frontend/security/dependabot/5

fix: fix semver vulnerability

---

packages/lib/src/components/Table/Table.module.css
packages/lib/src/components/Table/Table.tsx

Fixed darkmode style with two additional classes and a function to toggle specific classes based on current theme.
https://github.com/Frachtwerk/essencium-frontend/issues/446

fix: fix darkmode for rights

---

pull_request_template.md

In this PR the PR Template has been adjusted. 
There is a new checkbox for "check Vercel deployment" and the use of the closes keyword has been fixed. 
closes #493

refactor: adjust pr template

---

packages/app/.env
packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/api/me.ts
packages/app/src/pages/users/[id].tsx
packages/app/src/pages/users/index.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/PersonalDataForm.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/ProfileSettingsForm.tsx
packages/lib/src/components/Profile/components/ProfileOverviewCard.tsx
packages/lib/src/components/User/UserForm.tsx
packages/types/src/user.ts

The role property of the user object changed from a single role to a list of roles, so the user can now have multiple roles.
The following changes have been made: 
- Adjustment of the user types (UserInput, UserOutput, UserUpdate)
- Adjustments in UserForm, UserTable and ProfileView. 
closes #497

refactor: change role object of user to list of role objects

---

.github/ISSUE_TEMPLATE/issue.md
packages/app/MIGRATION.md
packages/docs/package.json
packages/docs/pages/_meta.json
packages/docs/pages/devguide/codestyle-and-linting.mdx
packages/docs/pages/devguide/pull-requests.mdx
packages/docs/pages/migrationguide.mdx
pnpm-lock.yaml

This PR contains the following changes:
- add migration guide section in docs and in dev guide
- fix broken links in docs
- update Nextra and Nextra docs theme to latest minor
- add further todo to GitHub issue template
Closes #513

513 add migration guide explanation in docs

---

packages/lib/package.json
pnpm-lock.yaml

Updating babel to 7.24.0
https://github.com/Frachtwerk/essencium-frontend/security/dependabot/15

chore: update babel

---

packages/lib/package.json
pnpm-lock.yaml

Update Postcss
closes https://github.com/Frachtwerk/essencium-frontend/security/dependabot/10

chore: update postcss

---

package.json
packages/docs/pages/migrationguide.mdx

This PR updates the migration guide page inside the documentation. 
Closes #529

529 update migration guide section in docs

---

packages/lib/src/components/Contact/Contact.test.tsx
packages/lib/src/components/Contact/components/ContactForm.tsx
packages/lib/src/components/Contact/components/ContactPersonCard.tsx

This PR updates existing tests.
Closes #533

test: update tests

---

.vscode/essencium-frontend.code-workspace
packages/lib/src/components/Login/components/LoginForm/LoginForm.test.tsx
packages/lib/src/components/Login/components/LoginForm/LoginForm.tsx
packages/lib/vitest.config.ts

This PR updates and adds tests to the `LoginForm.tsx` component.
Closes #501

501 lib validate existing tests for loginformtsx

---

packages/app/.env

This PR adjusts the app url to be mapped to the staging environment.

chore: adjust public app url to staging

---

packages/docs/pages/devguide.mdx
packages/docs/pages/devguide/_meta.json
packages/docs/pages/devguide/testing.mdx

This PR adds a "Testing" page to the docs.
Closes #517

docs: add tests page

---

packages/lib/src/components/SetPassword/SetPasswordForm.test.tsx

This PR fixes the existing test by wrapping the component to test in the mantine provider and app shell.
Closes #503

test: adjust test with mantine provider and app shell

---

packages/app/MIGRATION.md
packages/app/src/components/layouts/AuthLayout.tsx
packages/lib/src/components/Footer/Footer.tsx
packages/lib/src/components/Header/Header.module.css
packages/lib/src/components/Header/Header.tsx
packages/lib/src/components/Header/components/SearchBar/SearchBar.tsx
packages/lib/src/components/NavBar/NavBar.module.css
packages/lib/src/components/NavBar/NavBar.test.tsx
packages/lib/src/components/NavBar/NavBar.tsx

AppShell is refactored without any layout changes.
closes [536](https://github.com/Frachtwerk/essencium-frontend/issues/536)
closes [521](https://github.com/Frachtwerk/essencium-frontend/issues/521)
closes [514](https://github.com/Frachtwerk/essencium-frontend/issues/514)

536 refactor foldable navbar

---

packages/app/MIGRATION.md
packages/app/src/pages/users/index.tsx

Implement api-call for all users to filter entire data.
closes [556](https://github.com/Frachtwerk/essencium-frontend/issues/556)

fix: load all users for filter

---

packages/app/MIGRATION.md
packages/lib/src/components/Footer/Footer.module.css
packages/lib/src/components/NavBar/components/NavLinks.tsx

Highlight `NavLinks` also on specific child routes.
closes [545](https://github.com/Frachtwerk/essencium-frontend/issues/545)

545 highlight navlink in sidebar on child paths

---

packages/lib/src/components/Header/components/SearchBar/SearchBar.tsx
packages/lib/src/components/Header/components/ThemeSelector/ThemeSelector.tsx
packages/lib/src/components/Header/components/UserMenu/UserMenu.tsx
packages/lib/src/components/NavBar/NavBar.tsx

This PR adds the ability to add custom classes to components that are included inside the header. Also, a logo and icon is no longer mandatory to pass to the `NavBar.tsx` component.

Make some cmps customizable

---

.github/workflows/ci.yml
packages/app/MIGRATION.md
packages/app/e2e/HomeView.spec.ts
packages/app/e2e/LoginView.spec.ts
packages/app/e2e/NavBar.spec.ts
packages/app/e2e/ProfileView.spec.ts
packages/app/e2e/RolesView.spec.ts
packages/app/e2e/TranslationsView.spec.ts
packages/app/e2e/UsersView.spec.ts
packages/app/package.json
packages/app/playwright.config.ts
packages/app/playwright/lang.setup.ts
packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/lib/src/components/NavBar/NavBar.test.tsx
pnpm-lock.yaml

test: fix failing E2E tests

---

packages/app/e2e/RolesView.spec.ts
packages/app/e2e/UsersView.spec.ts

In this PR the E2E Tests for UsersView and RolesView have been fixed. 
closes #599

Fix E2E Tests

---

packages/app/MIGRATION.md

chore: update MIGRATION.md

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/lib/src/components/NavBar/NavBar.test.tsx
packages/lib/src/components/NavBar/NavBar.tsx
packages/lib/src/components/NavBar/components/NavLinks.tsx

In this PR the test für the component NavBar has been validated and extended.
closes #502

refactor: adjust test for NavBar

---

packages/app/src/components/layouts/AuthLayout.tsx
packages/lib/src/components/Footer/Footer.tsx
packages/lib/src/components/NavBar/NavBar.module.css
packages/lib/src/components/NavBar/NavBar.tsx

**Description**
1. **Navbar icon Adjustment:** Replace text logo in navbar with icon, visible when expanded and collapsed. 
3. **Footer Information:** Move version number and environment info from the navbar to the footer.
4. **Navbar menu Jumping Bug Fix:**  Fix menu items occasionally jumping.
**Scope**

625 navbar adjustments

---

packages/lib/src/components/NavBar/components/NavLinks.tsx
packages/types/src/navbar.ts

feat: add option to implement external links

---

packages/lib/src/components/Role/AddRole.tsx
packages/lib/src/components/Role/components/RoleForm.tsx

Adjust the role configuration to make custom roles fully editable.
closes https://github.com/Frachtwerk/essencium-frontend/issues/649

Make Custom Roles Editable

---

.github/workflows/ci.yml

This PR updates all GitHub actions dependencies as well as upgrades Node to version 22 (latest LTS).

update github action dependencies

---

packages/types/src/user.ts

feat: add password strength meter to user profile

---

packages/lib/package.json
packages/types/package.json
pnpm-lock.yaml

Fix vulnerability
closes https://github.com/Frachtwerk/essencium-frontend/security/dependabot/67

chore: fix rollup vulnerability

---

package.json
packages/app/.env
packages/app/public/runtimeConfig.js
packages/app/src/api/api.ts
packages/app/src/app/[locale]/(public)/login/LoginView.tsx
packages/app/src/components/provider/mantineProvider.tsx
packages/app/src/instrumentation.ts
packages/app/src/types.ts
packages/app/src/utils/index.ts
packages/app/src/utils/isBrowserEnvironment.test.ts
packages/app/src/utils/isBrowserEnvironment.ts
packages/docs/package.json
packages/docs/pages/architecture/runtime-config.mdx

This MR fixes the OAuth redirect variable that was missing and adds a section inside the docs how to disable the runtime config.

fix runtime config for oauth redirect url

---

packages/app/next.config.js

optimize mantine in dev and enable tree shaking

---

packages/docs/package.json
packages/docs/pnpm-lock.yaml

Fix next.js vulnerability
closes https://github.com/Frachtwerk/essencium-frontend/security/dependabot/84

fix next vulnerability

---

.github/workflows/ci.yml

remove trivy in favor of dependabot

remove trivy in favor of dependabot

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/lib/src/components/Header/Header.module.css
packages/lib/src/components/Header/Header.tsx
packages/lib/src/components/User/UserForm.tsx

https://github.com/Frachtwerk/essencium-frontend/issues/659

Add / edit user form checkbox

---

packages/lib/src/components/Header/Header.module.css
packages/lib/src/components/Header/Header.tsx

https://github.com/Frachtwerk/essencium-frontend/issues/667

notification in profile view & translation view is under app bar

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/lib/src/components/Role/components/RoleForm.tsx
packages/types/src/role.ts

This PR removes the min length contraint from the description field for creating / updating a role.

remove required role description

---

package.json
packages/app/MIGRATION.md
packages/app/src/app/[locale]/(main)/profile/ProfileView.tsx
packages/app/src/components/layouts/AuthLayout.tsx

Ensure the URL updates dynamically when the language is changed.
Automatically apply user updates in the UI without requiring a full page reload.

update URL on language change and auto-refresh user updates

---

packages/app/e2e/RightsView.spec.ts
packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/app/[locale]/(main)/admin/rights/RightsView.tsx
packages/app/src/app/[locale]/(main)/admin/roles/RolesView.tsx
packages/app/src/app/[locale]/(main)/admin/users/UsersView.tsx

Remove all refresh buttons and unused functions.
closes https://github.com/Frachtwerk/essencium-frontend/issues/666

Remove "refresh data" button in table views

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/app/[locale]/(main)/contact/ContactView.tsx
packages/lib/src/components/Contact/Contact.test.tsx
packages/lib/src/components/Contact/Contact.tsx
packages/lib/src/components/Contact/components/ContactPersonCard.module.css
packages/lib/src/components/Contact/components/ContactPersonCard.tsx
packages/lib/src/components/Header/components/ThemeSelector/ThemeSelector.module.css
packages/lib/src/components/Header/components/ThemeSelector/ThemeSelector.tsx
packages/lib/src/components/Header/components/UserMenu/UserMenu.tsx
packages/lib/src/components/Profile/components/ProfileOverviewCard.test.tsx
packages/lib/src/components/Profile/components/ProfileOverviewCard.tsx
packages/types/src/contact.ts

- remove avatar from contact person card and updates related tests
- add example contact person data for testing
- enhances theme selector with hover effects
- replaces icon with avatar in user menu and profile overview card
closes https://github.com/Frachtwerk/essencium-frontend/issues/698

implement avatar initials

---

pnpm-lock.yaml

See https://github.com/Frachtwerk/essencium-frontend/security/dependabot/97
closes https://github.com/Frachtwerk/essencium-frontend/security/dependabot/97

fix: fix esbuild vulnerability

---

packages/app/MIGRATION.md
packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/app/[locale]/(main)/contact/ContactView.tsx
packages/lib/src/components/Contact/components/ContactForm.module.css
packages/lib/src/components/Contact/components/ContactForm.tsx
packages/types/src/contact.ts

In this PR the ContactView has been refactored: 
* ~~the input fields for name and email are now prefilled with the data of the logged in user~~
* the input fields for name and email have been removed from the form and the respective values are set implicitly
* the styling of the input fields "subject" and "message" has been adjusted and is now the same as email and name 
closes #669

Refactor ContactPage

---

packages/app/package.json
packages/docs/pnpm-lock.yaml
packages/lib/package.json
pnpm-lock.yaml

Fix https://github.com/Frachtwerk/essencium-frontend/security/dependabot/98 and https://github.com/Frachtwerk/essencium-frontend/security/dependabot/97

fix(frontend): fix vite vulnerability

---

packages/app/src/components/layouts/AuthLayout.module.css
packages/app/src/components/layouts/AuthLayout.tsx

Scrollbars are displayed on every page

---

packages/app/MIGRATION.md

docs: update migration docs

---

packages/app/MIGRATION.md
packages/app/src/app/[locale]/(main)/admin/users/Users.module.css
packages/app/src/config/Theme.module.css
packages/app/src/config/mantine.ts
packages/lib/src/components/Profile/components/ProfileDataCard/ProfileDataCard.module.css
packages/lib/src/components/Profile/components/ProfileOverviewCard.module.css

Change default background color for all cards in dark mode.
closes #763

Consistent background for all cards in darkmode

---

packages/app/MIGRATION.md
packages/app/src/components/layouts/AuthLayout.tsx
packages/lib/src/components/NavBar/NavBar.module.css
packages/lib/src/components/NavBar/NavBar.tsx
packages/lib/src/components/NavBar/components/NavLinks.tsx

navbar pin icon problems

---

packages/app/package.json
packages/lib/package.json
pnpm-lock.yaml

The vite package has been updated to version 6.2.6 to fix the following security issues: 
* https://github.com/Frachtwerk/essencium-frontend/security/dependabot/130
* https://github.com/Frachtwerk/essencium-frontend/security/dependabot/131
* https://github.com/Frachtwerk/essencium-frontend/security/dependabot/129
closes #779

fix: fix vulnerability in vite package

---

packages/app/MIGRATION.md
packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/lib/src/components/User/UserForm.tsx

feat: add warning when changing a users password

---

packages/lib/src/components/Table/Table.module.css
packages/lib/src/components/Table/Table.tsx
packages/lib/src/components/Table/components/TableHeader.module.css
packages/lib/src/components/Table/components/TableHeader.tsx
packages/lib/src/components/Table/components/index.ts

This PR adds renders an icon on hover for sortable columns in the table component.  
As the implementation of the header has grown a bit, I also decided to extract it in a separate component.
Tests are pending until we decided on a testing strategy
closes #736

feat: indicate sortable table columns

---

packages/app/MIGRATION.md

The Migration Guide has been updated due to a new release.

Update MIGRATION.md for release

---

packages/app/MIGRATION.md
packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/types/src/feedback.ts

778 feedback widget missing german error messages

---

packages/app/MIGRATION.md
packages/app/src/app/[locale]/(public)/login/LoginView.tsx

frachtwerk logo for sso logins is missing in firefox

---

packages/app/MIGRATION.md
packages/app/src/app/[locale]/(main)/admin/users/UsersView.tsx

fix: load all roles for the roles filter in the users view

---

packages/lib/src/components/LoginForm/LoginForm.tsx

the link is now technically a button while looking like a link
closes #830

fix(lib): :bug: fix focus problem with resetPassword link

---

packages/app/MIGRATION.md
packages/app/e2e/UsersView.spec.ts
packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/app/[locale]/(main)/admin/users/UsersView.tsx
packages/lib/src/components/Table/components/TableHeaderColumn.tsx

icons indicating the active state of a user now have aria labels

fix(app): :wheelchair: improved accessibility for users view table

---

packages/lib/src/components/Role/AddRole.tsx
packages/lib/src/components/Role/EditRole.tsx

fix: :wheelchair: add aria-label to add and edit role modal close button

---

packages/app/MIGRATION.md
packages/app/src/globals.css
packages/lib/package.json
packages/lib/rollup.config.js

880 tailwindcss import globalscss from lib

---

packages/app/MIGRATION.md
packages/app/src/globals.css
packages/lib/package.json
packages/lib/rollup.config.js

fix: change import of lib css to flat styles.css

---

packages/app/MIGRATION.md
packages/app/src/globals.css
packages/lib/package.json
packages/lib/rollup.config.js

fix: :bug: fixed a bug importing globals.css in production

---

packages/lib/src/components/NavBar/NavBar.tsx

fix(lib): :wheelchair: improve navbar accessibility
