Frachtwerk/essencium-frontend

.github/workflows/ci.yml

Add Trivy repo scan job in pipeline to achieve more security and receive relevant information about vulnerabilities.
**CLOSES**
Closes #373

ci: add Trivy repo scan job

---

packages/lib/src/components/NavBar/components/NavLinks.tsx

**DESCRIPTION:**
When collapsing the sidebar, longer labels will not wrap anymore. 
**CLOSES:**
#375

Prevent line break when collapsing nav bar

---

.husky/pre-commit
.lintstagedrc.json
package.json
pnpm-lock.yaml

This PR adds lint-staged to the codebase. It runs prettier (in write-mode) and eslint (dry-run) for the pattern `**/*.{js,jsx,ts,tsx}` and sort-package-json for alle `package.json` files.
**CLOSES**
Closes #341

chore: add lint-staged for eslint, prettier and sort-package-json

---

packages/app/package.json
packages/app/src/pages/_document.tsx
pnpm-lock.yaml

This PR fixes the layout flickering on initial page load by utilising the `@mantine/next` and  package. Additionally, the `_documents.ts` file has been modified. It now takes the initial props on the server to render the HTML with the CSS inside (image is from the response of the HTML document):
**CLOSES**
Closes #365

fix: fix layout flickering by using mantine ssr package

---

packages/app/src/pages/rights/index.tsx

**DESCRIPTION:**
The roles were fetched based on the page number and because of that there were no roles to display on page two and onwards. The page number has been set to zero now to get all roles.  
Closes #361

fix: set page number to zero when fetching roles

---

packages/docs/pages/architecture.mdx
packages/docs/pages/devguide/dependencies.mdx
renovate.json

This PR removes Renovate in favour of Dependabot which is built-in inside GitHub. I removed the Renovate config file and updated the docs. accordingly. Additionally I cleaned up the repo:
- closed all Renovate pull requests --> Dependabot creates own ones (currently configured only for `HIGH` vulnerabilities)
- 
**CLOSES**
Closes #404

refactor: remove Renovate in favour of Dependabot

---

packages/lib/src/components/Profile/Profile.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/ProfileDataCard.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/PasswordChangeForm.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/PersonalDataForm.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/ProfileSettingsForm.tsx
packages/lib/src/components/Role/AddRole.tsx
packages/lib/src/components/Role/EditRole.tsx
packages/lib/src/components/Role/components/RoleForm.tsx
packages/lib/src/components/User/UserForm.tsx
packages/lib/src/views/AddUserView.tsx
packages/lib/src/views/ProfileView.tsx
packages/lib/src/views/RolesView.tsx
packages/lib/src/views/UpdateUserView.tsx

**DESCRIPTION:**
A loading state has been added to the submit buttons in 
- Add Users & Update Users  
- Add Roles & Update Roles 
- Update Profile: Personal Data, Password and Settings 
While the button is in loading state, the icon is replaced with the loading spinner and the button gets disabled with a light overlay. 
Closes #405

feat: add loading state to buttons

---

packages/lib/src/components/NavBar/NavBar.tsx
packages/lib/src/layouts/AuthLayout.tsx

In this PR the margin in the AuthLayout has been adjusted, so that there is no unnecessary margin on smaller screen sizes. Additionally the color for the icon to fix the menu has been adjusted to dark mode. 
closes #433

fix: adjust margin in AuthLayout for mobile screens

---

packages/lib/src/layouts/AuthLayout.tsx
packages/lib/src/views/LoginView.tsx

In this PR the margin in the AuthLayout and LoginView has been adjusted, so that the user is redirected to the desired path after login.
First, if the user is not logged in the 'redirect' params are set while user is forwarded to login. In LoginView the user is forwarded to the path in the redirect params after successful login.
Closes #440

feat: use params to redirect after login

---

packages/docs/pages/devguide/_meta.json
packages/docs/pages/devguide/codestyle-and-linting.mdx

This PR updates the section [Code style and linting](https://docs.essencium.dev/devguide/codestyle-and-linting) by adding an explanation for the used Prettier rules and other minor changes.
**CLOSES**
Closes #394

docs: update codestyle and linting page

---

packages/docs/pages/architecture.mdx
packages/docs/pages/devguide/codestyle-and-linting.mdx
packages/docs/pages/devguide/packageResponsibilities.mdx

This PR updates the sections where we describe the architecture or the monorepo packages since we had several changes in the near past. Additionally, I added some links to relevant keywords.
- ~~implement and update tests~~
#454

docs: update architecture sections and config package links

---

packages/lib/src/components/FeedbackWidget/FeedbackWidget.tsx

In this PR the color of the action icons in the feedback widget has been changed. A hardcoded color string led to issues in Essencium based projects. By using the primary theme color, this should be solved. 
closes #508

refactor: change color from string to theme color

---

packages/app/src/pages/profile/index.tsx
packages/app/src/pages/rights/index.tsx
packages/app/src/pages/roles/index.tsx
packages/app/src/pages/users/index.tsx
packages/lib/src/components/FeedbackWidget/FeedbackWidget.tsx
packages/lib/src/components/LoadingSpinner/LoadingSpinner.tsx
packages/lib/src/components/Login/components/LoginForm/LoginForm.tsx

In this PR, the LoadingSpinner component has been customized: 
- it can now consume all Mantine component props
- it is centered vertically and horizontally on the page
- all default Loader components have been exchanged with the LoadingSpinner component 
closes #444

feat: customize LoadingSpinner Component

---

packages/lib/src/components/FeedbackWidget/FeedbackWidget.module.css
packages/lib/src/components/FeedbackWidget/FeedbackWidget.tsx

The feedback widget now gets closed on screen capture and opens again after the screenshot is made. 
closes #542

feat: close feedback widget on screen capture

---

packages/app/src/utils/withBaseStylingShowNotification.ts

Since the Mantine Update the notifications were displayed beneath the header and therefore were hard to read. In this PR the style of the notification component has been adjusted, so that it is displayed correctly. 
closes #558

fix: adjust z-index for notification

---

package.json
pnpm-lock.yaml

Update `commitlint` packages with peer dep `semver` which is has a vulnerability.
closes https://github.com/Frachtwerk/essencium-frontend/security/dependabot/3

chore: update commitlint packages that caused semver vulnerabilities

---

packages/app/MIGRATION.md
packages/app/src/components/layouts/AuthLayout.module.css
packages/app/src/components/layouts/AuthLayout.tsx
packages/lib/src/components/Footer/Footer.tsx
packages/lib/src/components/Header/Header.tsx
packages/lib/src/components/NavBar/NavBar.tsx
packages/lib/src/components/Table/Table.tsx

This PR enables the ability to pass all Mantine props to our custom components that forward them to the Mantine components. The win here is much higher customizability.

feat: enable props forwarding for appshell mantine components

---

packages/app/MIGRATION.md
packages/app/src/components/layouts/AuthLayout.tsx
packages/lib/src/components/FeedbackWidget/FeedbackWidget.tsx
packages/lib/src/components/Footer/Footer.module.css
packages/lib/src/components/Footer/Footer.tsx

FeedbackWidget is moved to footer as child
closes #584

fix: move feedbackWidget to footer

---

packages/lib/src/components/Header/components/UserMenu/UserMenu.tsx

This PR adds the ability to pass a custom class to the `UserMenu.tsx` component's unstyled button.

fix: allow passing classes to button component

---

packages/app/src/components/layouts/AuthLayout.tsx
packages/app/src/components/layouts/PublicLayout.tsx

This PR removes the hard-coded title for layout files and replaces them with a i18n variable (`header.title`)

fix: replace hard-coded app name with i18n variable

---

packages/lib/src/components/Table/Table.module.css
packages/lib/src/components/Table/Table.tsx

The first table column is currently always sticky. This PR fixes the bug.
-

fix(frontend): set first table col only sticky on concerning prop

---

packages/app/MIGRATION.md
packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/components/layouts/AuthLayout.tsx
packages/app/src/pages/api/feedback.ts
packages/lib/src/components/FeedbackWidget/FeedbackWidget.module.css
packages/lib/src/components/FeedbackWidget/FeedbackWidget.test.tsx
packages/lib/src/components/FeedbackWidget/FeedbackWidget.tsx
packages/lib/src/components/LoginForm/LoginForm.module.css
packages/lib/src/components/LoginForm/LoginForm.tsx
packages/types/src/feedback.ts

In this PR the FeedbackWidget Component has been refactored. Now its possible to give an arbitrary number of key value pairs as prop to the FeedbackWidget. This customizable additional information will be added to the email to provide more context (e.g. user language, user roles, environment, software version etc.)
closes #554

refactor: pass arbitrary number of key value pairs to feedback widget

---

packages/docs/pages/_meta.json
packages/docs/pages/maintainerguide/_meta.json
packages/docs/pages/maintainerguide/release-process.mdx

This PR adds the documentation for the Essencium release process.
Closes #576

docs: add release process documentation

---

packages/app/src/pages/_app.tsx
packages/lib/src/components/Header/components/ThemeSelector/ThemeSelector.module.css
packages/lib/src/components/Header/components/ThemeSelector/ThemeSelector.tsx
packages/lib/src/components/Translations/Translations.tsx

In this PR the following functionality has been added: 
* In the themeSelector dropdown the currently active theme is now indicated (via highlighted row and text-color)
* The themeSelector Icon is now displayed in the primary color, when the theme has been changed manually to dark or light. If the system theme is used, the icon is in a neutral color. 
closes #492

refactor: indicate selected color theme in dropdown and icon

---

packages/app/MIGRATION.md
packages/lib/src/components/User/UserForm.tsx

If a user account has been created via a sso provider, all input fields in the userForm were disabled by default. Therefor the roles of sso users could not be updated. 
In this PR the disabled prop for the roles input in the UserForm has been made configurable. The default is still disabled, but it can be enabled via prop. Since different projects can have different approaches regarding the roles update process it is helpful, if the input field for roles can be enabled, if needed. 
closes #618

refactor: make roles input configurable

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/lib/src/components/TablePagination/TablePagination.module.css
packages/lib/src/components/TablePagination/TablePagination.tsx

This PR adds the functionality to jump to a specific page in table views. You can test it inside the user view, set the max page size to 10 to have 2 pages and jump via the text input back and forth.

add ability to jump to a specific page

---

packages/app/src/components/layouts/AuthLayout.tsx
packages/lib/src/components/NavBar/NavBar.tsx
packages/lib/src/components/NavBar/components/NavLinks.module.css
packages/lib/src/components/NavBar/components/NavLinks.tsx
packages/types/src/navbar.ts

This PR adds support for sub menu items, by appending a recursive `navItems` array inside a nav item.

add support for sub nav items

---

packages/types/src/feedback.ts

This PR makes the `screenshot` property optional.

fix: set screenshot type optinal

---

packages/app/src/app/[locale]/(main)/layout.tsx
packages/app/src/app/[locale]/page.tsx
packages/app/src/components/RouteProtector.tsx

Since the pathname also contains the locale (if it is not the defaultLocale), the locale needs to be removed in order to check for the respective page rights.
**Testing:** 
* Login in with devnull_user@frachtwerk.de
* Go to /users or /roles 
* RouterProtector should be rendered correctly
* Change language and test again 
closes #644

fix: fix pathname in RouteProtector

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/app/[locale]/(main)/rights/RightsView.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/ProfileDataCard.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/PasswordChangeForm.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/PasswordRequirement.module.css
packages/lib/src/components/Profile/components/ProfileDataCard/components/PasswordRequirement.test.tsx
packages/lib/src/components/Profile/components/ProfileDataCard/components/PasswordRequirement.tsx
packages/types/src/user.ts

In this PR a component has been added to the changePassword tab in the user profile. It indicates whether the necessary requirements for new passwords are met.
The requirements currently are:
* min length 12 char, for admins 20 char
* min 1 upper case letter
* min 1 lower case letter
* min 1 symbol
* min 1 number
closes #653

Add password strength meter to user profile

---

packages/lib/src/components/Profile/components/ProfileDataCard/components/PersonalDataForm.module.css

This merge request fixes the layout issue on the profile page in mobile view, where error messages for first name and last name overlapped with phone number and mobile number labels.

fix: error message overlap on profile page in mobile view

---

packages/app/.env
packages/app/public/runtimeConfig.js
packages/app/src/components/layouts/AuthLayout.tsx
packages/app/src/instrumentation.ts
packages/app/src/types.ts
packages/lib/src/components/Footer/Footer.tsx
packages/lib/src/components/Header/Header.module.css
packages/lib/src/components/Header/Header.tsx

This PR refactors the version and environment indicator. The version is now always shown inside the footer and derived from the project `package.json`.  The environment is implemented inside the runtime config and visualized inside the header component beside the theme switcher.

Refactor version and env indicator

---

packages/app/src/app/[locale]/(main)/admin/rights/RightsView.tsx
packages/app/src/app/[locale]/(main)/admin/roles/RolesView.tsx
packages/app/src/app/[locale]/(main)/admin/users/UsersView.tsx
packages/lib/src/components/TablePagination/TablePagination.test.tsx
packages/lib/src/components/TablePagination/TablePagination.tsx

This PR fixes the bug where the request on page change for table views is fired twice due to invoking `handleRefetch` and the re-rendering of the affected component which as well causes a refetch. Hence, the manual `handleRefetch` callback is not necessary.
This will be breaking for essenciun-based projects.

fix: remove handle refetch that causes duplicate requests

---

packages/app/src/app/[locale]/(main)/admin/rights/RightsView.tsx

In the Tableheader on the RightsView page the name of the role is displayed instead of a translation. 
closes #660

fix: fix role name in tableHeader of RightsView

---

packages/app/MIGRATION.md
packages/app/src/app/[locale]/(main)/HomeView.tsx
packages/lib/src/components/Home/Home.tsx

The following was implemented in this PR: 
The `USER_READ` right is checked on the `HomeView` in order to render the button for the `UserView`.
closes #668

fix: show buttons depending on rights on home page

---

packages/app/.env
packages/app/MIGRATION.md
packages/app/public/runtimeConfig.example.js
packages/app/src/app/[locale]/(main)/admin/users/UsersView.tsx
packages/app/src/instrumentation.ts
packages/app/src/types.ts

The initial admin user should be protected and not be deleteable in the UI. Currently the defaultUser is defined by the name. This should be changed to the email. The email should be configurable via the runtimeConfig.
- add DEFAULT_USER_EMAIL and NEXT_PUBLIC_DEFAULT_USER_EMAIL env for undeletable default user

chore: add DEFAULT_USER_EMAIL env for undeletable default user

---

packages/app/package.json
packages/lib/package.json
pnpm-lock.yaml

Patch vitest version to 2.1.9 and fix vulnerability.
closes https://github.com/Frachtwerk/essencium-frontend/security/dependabot/96

fix: fix vulnerability vitest

---

packages/app/MIGRATION.md
packages/app/src/api/api.ts

If the session token expires or is terminated, the user is automatically logged out when navigating the site. 
Now the target page is persisted in the URL so that the user lands directly on the desired page again after logging in again.
closes #715

Persist target page in url when session token expires

---

packages/app/src/app/[locale]/(main)/admin/users/UsersView.tsx

The active column can be enhanced visually with a more appealing indicator, such as a custom icon or different color scheme, to make it stand out.
[665](https://github.com/Frachtwerk/essencium-frontend/issues/665)

beautify 'active' state in user table 

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/lib/src/components/User/UserForm.module.css
packages/lib/src/components/User/UserForm.tsx

* In the form to add a new user is now a tooltip, that explains what happens when the password field stays empty. 
* The style of the input fields has been adjusted. The styling is now the same as in profileView, ContactView etc.
closes #650

Add hint for password setting process in userForm

---

packages/docs/package.json
packages/docs/pnpm-lock.yaml

This PR bumps [next](https://github.com/vercel/next.js) in the docs package from  "14.2.23" to "14.2.25".
--> fixes https://github.com/advisories/GHSA-f82v-jwr5-mffw

Update nextjs in docs to 14.2.25

---

packages/app/public/locales/de/common.json
packages/app/public/locales/en/common.json
packages/app/src/app/[locale]/(main)/legal-notice/LegalNoticeView.module.css
packages/app/src/app/[locale]/(main)/legal-notice/LegalNoticeView.tsx
packages/app/src/app/[locale]/(main)/legal-notice/page.tsx
packages/app/src/app/[locale]/(main)/privacy-policy/PrivacyPolicyView.module.css
packages/app/src/app/[locale]/(main)/privacy-policy/PrivacyPolicyView.tsx
packages/app/src/app/[locale]/(main)/privacy-policy/page.tsx
packages/app/src/components/layouts/AuthLayout.tsx

Implements sample pages in app for privacy policy and legal notice.
closes #651

651 add datenschutz privacy policy and impressum legal notice pages

---

packages/app/MIGRATION.md
packages/lib/src/components/Contact/Contact.tsx
packages/lib/src/components/Contact/components/ContactPersonCard.tsx
packages/types/src/contact.ts

Currently telephone, address, and social media is required for contact. Values can be set du null but then defaults will be used. 
Instead there should be a minimum of required values (mail and name) and everything thats not set is not rendered.

fix: set only name and mail as required in contact data

---

packages/lib/src/components/Header/components/UserMenu/UserMenu.tsx
packages/lib/src/components/NavBar/components/NavLinks.tsx

Links with sublinks are handled as buttons, all other (normal links, sublinks themselves) are handled as NextLink.
closes https://github.com/Frachtwerk/essencium-frontend/issues/758

758 child navitems not accessible in e2e tests and mobile view

---

packages/lib/src/components/NavBar/components/NavLinks.tsx

fix active states for nav items

---

packages/app/MIGRATION.md
packages/app/src/app/[locale]/(main)/admin/users/UsersView.tsx

This fixes the sorting of the user table by name.
The property `name` does not exist in the backend payload, instead either `firstName` or `lastName` have to be used. As the default sorting is done by `firstName`, I picked it here as well.
A test for this will be added in the scope of #682.
closes #772

fix(frontend): fix sorting by name of user table (#772)

---

packages/app/package.json
packages/lib/package.json
pnpm-lock.yaml

Vite package is updated to 6.2.7 to resolve this [CVE](https://github.com/Frachtwerk/essencium-frontend/security/dependabot/133).
closes #792

fix(frontend): fix vulnerability in vite package

---

pnpm-lock.yaml

In this PR the packages for brace-expansion have been updated to the latest fixed version due to this [CVE](https://github.com/Frachtwerk/essencium-frontend/security/dependabot/135).
As it is a transitive dependency is has been updated in the lockfile.

chore(frontend): update brace-expansion packages

---

packages/app/e2e/HomeView.spec.ts
packages/app/e2e/LoginView.spec.ts
packages/app/e2e/NavBar.spec.ts
packages/app/e2e/ProfileView.spec.ts
packages/app/e2e/RightsView.spec.ts
packages/app/e2e/RolesView.spec.ts
packages/app/e2e/TranslationsView.spec.ts
packages/app/e2e/UsersView.spec.ts
packages/app/e2e/title.spec.ts
packages/app/playwright.config.ts
packages/app/playwright/auth.setup.ts
packages/app/playwright/lang.setup.ts

This PR configures the [baseUrl](https://playwright.dev/docs/test-webserver#adding-a-baseurl) for Playwright and removes the now unnecessary imports of our exported `BASE_URL`.
The only test that covers a different site is a skipped test in `title.spec.js` that checks the page title of our deployed docs. As the test currently fails (because our docs don't have a page title right now), it seems to be kind of unimportant and it would better be moved to `packages/docs`, I decided to ignore this for now.
Closes #820.

chore(e2e): configure playwright baseUrl

---

packages/app/MIGRATION.md
packages/app/src/app/[locale]/(main)/admin/users/UsersView.tsx

This PR essentially reverts the changes from #773.
In https://github.com/Frachtwerk/essencium-backend/pull/721, the missing support for sorting by the `name`-property has been added, so now both sorting and filtering of users do work by `name`.
Closes #783.

fix(app): adjust users sorting by name
